image: nfcore/gitpod:latest

vscode:
  extensions: # minimal helpful extensions from nf-core suggestions.
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
