# Use the nf-core Gitpod image located at https://github.com/nf-core/tools/blob/master/nf_core/gitpod/gitpod.Dockerfile
image: nfcore/gitpod:latest

# Gitpod definition file adapted from:
#  - https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.gitpod.yml
#  - https://github.com/nextflow-io/training/blob/master/.gitpod.yml

tasks:
  # TODO: Do we remove this task? Used to preview Carpentries page build
  - name: Install local page serve
    init: |
      sudo apt-get install -y ruby ruby-dev build-essential libxml2-dev
      sudo gem install bundler
  # Update Nextflow if image version is behind
  - name: Update Nextflow and setup pre-commit
    command: |
      # pre-commit install --install-hooks
      nextflow self-update
      unset JAVA_TOOL_OPTIONS
  # Install additional tools
  - name: Install tools for the exercises.
    command: |
      conda install --yes --update-all \
        salmon=1.5 \
        fastqc=0.11 \
        multiqc=1.10 \
      && conda clean --all --force-pkgs-dirs --yes

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - cssho.vscode-svgviewer # SVG viewer
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    # - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - ms-vscode.live-server
