# This playbook prepares images for the Nextflow Ed-DASH course. For EdGe EC2 images,
# just start any number of regular training VMs, and check they exist with:
#
#  $ ansible-inventory --graph --verbose
#
# If other VMs are running then you'll need to do something smarter.
#
- hosts: dash
  become: true
  become_user: training
  tasks:

    - name: Set alternative password for VNC
      when: false
      vars:
        passwd: "ed-dash-1307"
      become_user: training
      shell:
        executable: /bin/bash
        chdir: ~/.vnc
        cmd: |
             set -euo pipefail
             mv passwd passwd.old
             echo '{{ passwd }}' | /opt/tigervnc/usr/bin/vncpasswd -f > passwd
             chmod 0600 passwd
      args:
        creates: ~/.vnc/passwd.old

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/Downloads
        state: directory
        mode: '0755'

    - name: Fetch Miniconda Installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
        dest: ~/Downloads/miniconda3_installer.sh
        mode: '0644'
        checksum: sha256:536817d1b14cb1ada88900f5be51ce0a5e042bae178b5550e62f61e223deae7c

    - name: Run Miniconda Installer
      shell:
        executable: /bin/bash
        chdir: ~/
        cmd: |
             set -euo pipefail
             rm -rf ~/.conda ~/miniconda3
             bash ~/Downloads/miniconda3_installer.sh -b
             source ~/miniconda3/bin/activate
             conda init
        creates: ~/.conda/environments.txt

    # I could do a full checkout of the GitHub repo here?
    # No checksum - the file may change
    - name: Download conda env spec
      get_url:
        url: https://raw.githubusercontent.com/ggrimes/workflows-nextflow/gh-pages/files/conda_env_all.yaml
        dest: ~/Downloads/nextflow_conda_env.yaml
        mode: '0644'
        backup: yes

    - name: Bootstrap deps into base env
      when: false
      shell:
        executable: /bin/bash
        chdir: ~/
        cmd: |
             set -euo pipefail
             source ~/miniconda3/bin/activate
             conda install -c conda-forge -c bioconda nextflow=21
             nextflow -version > ~/Downloads/nextflow_version.txt
        creates: ~/Downloads/nextflow_version.txt

    - name: Set nf conda environment
      when: true
      shell:
        executable: /bin/bash
        chdir: ~/
        cmd: |
             set -euo pipefail
             source ~/miniconda3/bin/activate
             conda env create -n nf --file ~/Downloads/nextflow_conda_env.yaml
             conda activate nf
             nextflow -version
        creates: ~/miniconda3/envs/nf


    - name: Download the data files
      get_url:
        url: https://ndownloader.figshare.com/files/28531743
        dest: ~/Downloads/nextflow_data.tar.gz
        mode: '0644'
        backup: no

    - name: Unpack the data files
      unarchive:
        src: ~/Downloads/nextflow_data.tar.gz
        dest: ~/
        remote_src: yes
        creates: /home/training/data
