# This playbook prepares images for the Nextflow Ed-DASH course. For EdGe EC2 images,
# just start any number of regular training VMs, and check they exist with:
#
#  $ ansible-inventory --graph --verbose
#
# If other VMs are running then you'll need to do something smarter.
# https://codeforgeek.com/install-atom-editor-ubuntu-14-04/
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- hosts: dash
  become: yes
  become_user: ubuntu
  tasks:
    - name: Update repositories cache and install "gpg-agent" editor using apt
      become_user: root
      apt:
        name: gpg-agent
        update_cache: yes

    - name: Add an Apt signing key, uses whichever key is at the URL
      become_user: root
      apt_key:
        url: https://packagecloud.io/AtomEditor/atom/gpgkey
        state: present


    - name: Add atom source repository into sources list
      become_user: root
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
        state: present

    - name: Update repositories cache and install "atom" editor using apt
      become_user: root
      apt:
        name: atom
        update_cache: yes

#    - include: atom-one-package.yml
#      with_items: "{{req_packages}}"
#    - name: Install atom editor  (state=present is optional)
#      apt:
#        deb: https://github.com/atom/atom/releases/download/v1.58.0/atom-amd64.deb
#        name: atom
#        state: present
