name: nextflow_dash
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - salmon=1.5.2
  - fastqc=0.11.9
  - multiqc=1.11
  - kallisto=0.46.2
  - fastq-tools
  - samtools=1.13
  - nextflow=21.04.0
  - nf-core=2.0.1
  - graphviz=2.48.0
  - python=3.9.6
